GET http://localhost:5007/api/all-products

###
POST http://localhost:5007/api/add-customer
Content-Type: application/json
# Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjUyNmM2YTg0YWMwNjcwMDVjZTM0Y2VmZjliM2EyZTA4ZTBkZDliY2MiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZWNvbW1lcmNlLXBheW1lbnQtZGEzNjUiLCJhdWQiOiJlY29tbWVyY2UtcGF5bWVudC1kYTM2NSIsImF1dGhfdGltZSI6MTcwMzg1MDYzMiwidXNlcl9pZCI6InpkZGZ0MzJaSTBneTFtdmF3OUhsNUtMTGg2QzIiLCJzdWIiOiJ6ZGRmdDMyWkkwZ3kxbXZhdzlIbDVLTExoNkMyIiwiaWF0IjoxNzAzODUwNjMyLCJleHAiOjE3MDM4NTQyMzIsImVtYWlsIjoidGVzdDEyM0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsidGVzdDEyM0BnbWFpbC5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.EGnNexXD4l6H7bkdBqZTsjJ8wMNkrZboCAZ_LcarAH8tu0heWuBCN8j-ESIIs4yPhMpoAq5mAjjgZql31IOLnZDHcYXL-ZYMXIeiugOCOB-GHH2sRrTcGHbznbOkmOvLWwFwBl0HG6bg9ZAkcAjbSHvzwVmtc7gCSXGfJrGH4Mo1bM1ei4khkWgR3AJaH8xKQJLJz5eWd6q4TiaKb1ZE4tfLkzEXHQ_15wrPXXeVr7zguQLl_wJEa8aK2FBWDRI4IuhO1neAodz6VKA0xeSJMaWrTVj8oaBbizvvOZ3DPockLjo51avEi0TyVxiqWdz6NeaUl8Ersi9XwK33hvuMPA

{
    "name": "test",
    "email": "test123@gmail.com",
    "userId": "122"
}

###
POST http://localhost:5007/api/get-user-details
Content-Type: application/json

{
    "email": "test123@gmail.com"
}

